//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiraiNotes.Android.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiraiNotes.Android.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I hope you are enjoying using this app, if you would like to buy me a coffee/beer, just send me an email..
        /// </summary>
        public static string AboutDonations {
            get {
                return ResourceManager.GetString("AboutDonations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app uses Google Tasks to retrieve/update your task lists and tasks, it also allows you to interact with them offline and sync them later..
        /// </summary>
        public static string AboutSummary {
            get {
                return ResourceManager.GetString("AboutSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I made this app in my free time and it is also open source. If you would like to help me, report an issue, have an idea, want a feature to be implemented, etc please open an issue here:.
        /// </summary>
        public static string AboutSupport {
            get {
                return ResourceManager.GetString("AboutSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent Color.
        /// </summary>
        public static string AccentColor {
            get {
                return ResourceManager.GetString("AccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a reminder.
        /// </summary>
        public static string AddReminder {
            get {
                return ResourceManager.GetString("AddReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a subtask.
        /// </summary>
        public static string AddSubTask {
            get {
                return ResourceManager.GetString("AddSubTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Theme.
        /// </summary>
        public static string AppTheme {
            get {
                return ResourceManager.GetString("AppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask for fingerprint when the app starts.
        /// </summary>
        public static string AskForFingerprint {
            get {
                return ResourceManager.GetString("AskForFingerprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask for a password when the app starts.
        /// </summary>
        public static string AskForPassword {
            get {
                return ResourceManager.GetString("AskForPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At this hour.
        /// </summary>
        public static string AtThisHour {
            get {
                return ResourceManager.GetString("AtThisHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An automatic full sync was successfully performed.
        /// </summary>
        public static string AutomaticSyncWasPerformed {
            get {
                return ResourceManager.GetString("AutomaticSyncWasPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an accent color.
        /// </summary>
        public static string ChooseAccentColor {
            get {
                return ResourceManager.GetString("ChooseAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an app language.
        /// </summary>
        public static string ChooseAppLanguage {
            get {
                return ResourceManager.GetString("ChooseAppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a base app color.
        /// </summary>
        public static string ChooseAppTheme {
            get {
                return ResourceManager.GetString("ChooseAppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completition.
        /// </summary>
        public static string Completition {
            get {
                return ResourceManager.GetString("Completition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password cannot be empty.
        /// </summary>
        public static string ConfirmPasswordCantBeEmpty {
            get {
                return ResourceManager.GetString("ConfirmPasswordCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password does not match.
        /// </summary>
        public static string ConfirmPasswordDoesntMatch {
            get {
                return ResourceManager.GetString("ConfirmPasswordDoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password max length is {0}.
        /// </summary>
        public static string ConfirmPasswordMaxLength {
            get {
                return ResourceManager.GetString("ConfirmPasswordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred while consulting the database.
        /// </summary>
        public static string DatabaseUnknownError {
            get {
                return ResourceManager.GetString("DatabaseUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not delete the default account.
        /// </summary>
        public static string DefaultAccountCantBeDeleted {
            get {
                return ResourceManager.GetString("DefaultAccountCantBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default synchronization interval.
        /// </summary>
        public static string DefaultSyncInterval {
            get {
                return ResourceManager.GetString("DefaultSyncInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default tasklist sort order.
        /// </summary>
        public static string DefaultTasklistSortOrder {
            get {
                return ResourceManager.GetString("DefaultTasklistSortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default task sort order.
        /// </summary>
        public static string DefaultTaskSortOrder {
            get {
                return ResourceManager.GetString("DefaultTaskSortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete task.
        /// </summary>
        public static string DeleteTask {
            get {
                return ResourceManager.GetString("DeleteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wanna delete this task ?.
        /// </summary>
        public static string DeleteTaskConfirmation {
            get {
                return ResourceManager.GetString("DeleteTaskConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wanna delete this account ?.
        /// </summary>
        public static string DeleteThisAccountConfirmation {
            get {
                return ResourceManager.GetString("DeleteThisAccountConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard changes.
        /// </summary>
        public static string DiscardChanges {
            get {
                return ResourceManager.GetString("DiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donations.
        /// </summary>
        public static string Donations {
            get {
                return ResourceManager.GetString("Donations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint not recognized. Try again..
        /// </summary>
        public static string FingerprintAuthFailed {
            get {
                return ResourceManager.GetString("FingerprintAuthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm fingerprint to continue.
        /// </summary>
        public static string FingerprintAuthMsg {
            get {
                return ResourceManager.GetString("FingerprintAuthMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint is not available.
        /// </summary>
        public static string FingerprintIsNotAvailable {
            get {
                return ResourceManager.GetString("FingerprintIsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompleted.
        /// </summary>
        public static string Incompleted {
            get {
                return ResourceManager.GetString("Incompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid reminder date.
        /// </summary>
        public static string InvalidReminderDate {
            get {
                return ResourceManager.GetString("InvalidReminderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid reminder hour.
        /// </summary>
        public static string InvalidReminderHour {
            get {
                return ResourceManager.GetString("InvalidReminderHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date of the reminder must be at least 2 mins above the current time.
        /// </summary>
        public static string InvalidTaskRemindOn {
            get {
                return ResourceManager.GetString("InvalidTaskRemindOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background task could not be scheduled.
        /// </summary>
        public static string JobCouldntBeScheduled {
            get {
                return ResourceManager.GetString("JobCouldntBeScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background task was successfully scheduled.
        /// </summary>
        public static string JobWasScheduled {
            get {
                return ResourceManager.GetString("JobWasScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as {0}.
        /// </summary>
        public static string MarkTaskAs {
            get {
                return ResourceManager.GetString("MarkTaskAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark {0} as {1} ?.
        /// </summary>
        public static string MarkTaskAsConfirmation {
            get {
                return ResourceManager.GetString("MarkTaskAsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since you are moving an existing task to a different task list, any change made here that is not saved will be lost. Do you want to continue ?.
        /// </summary>
        public static string MoveTaskConfirmation {
            get {
                return ResourceManager.GetString("MoveTaskConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wanna move &apos;{0}&apos; to &apos;{1}&apos;  ?.
        /// </summary>
        public static string MoveTaskConfirmationB {
            get {
                return ResourceManager.GetString("MoveTaskConfirmationB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to a different task list.
        /// </summary>
        public static string MoveToDifferentTaskList {
            get {
                return ResourceManager.GetString("MoveToDifferentTaskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network is not available.
        /// </summary>
        public static string NetworkNotAvailable {
            get {
                return ResourceManager.GetString("NetworkNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network is not available, a full sync will not be performed.
        /// </summary>
        public static string NetworkNotAvailableForSync {
            get {
                return ResourceManager.GetString("NetworkNotAvailableForSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New SubTask.
        /// </summary>
        public static string NewSubTask {
            get {
                return ResourceManager.GetString("NewSubTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Task.
        /// </summary>
        public static string NewTask {
            get {
                return ResourceManager.GetString("NewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Task List.
        /// </summary>
        public static string NewTaskList {
            get {
                return ResourceManager.GetString("NewTaskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One day ago.
        /// </summary>
        public static string OneDayAgo {
            get {
                return ResourceManager.GetString("OneDayAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On this date.
        /// </summary>
        public static string OnThisDate {
            get {
                return ResourceManager.GetString("OnThisDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty.
        /// </summary>
        public static string PasswordCantBeEmpty {
            get {
                return ResourceManager.GetString("PasswordCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not match.
        /// </summary>
        public static string PasswordDoesntMatch {
            get {
                return ResourceManager.GetString("PasswordDoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is incorrect.
        /// </summary>
        public static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot have more than {0} characters.
        /// </summary>
        public static string PasswordMaxLength {
            get {
                return ResourceManager.GetString("PasswordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a task list.
        /// </summary>
        public static string PickTaskList {
            get {
                return ResourceManager.GetString("PickTaskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder.
        /// </summary>
        public static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder date cannot be empty.
        /// </summary>
        public static string ReminderDateCannotBeEmpty {
            get {
                return ResourceManager.GetString("ReminderDateCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A reminder date was set to the {0}.
        /// </summary>
        public static string ReminderDateIsSetTo {
            get {
                return ResourceManager.GetString("ReminderDateIsSetTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder hour cannot be empty.
        /// </summary>
        public static string ReminderHourCannotBeEmpty {
            get {
                return ResourceManager.GetString("ReminderHourCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder was successfully created.
        /// </summary>
        public static string ReminderWasCreated {
            get {
                return ResourceManager.GetString("ReminderWasCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run a full sync after switching accounts.
        /// </summary>
        public static string RunFullSyncAfterSwitchingAccounts {
            get {
                return ResourceManager.GetString("RunFullSyncAfterSwitchingAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run a full sync when the app starts.
        /// </summary>
        public static string RunFullSyncWhenAppStarts {
            get {
                return ResourceManager.GetString("RunFullSyncWhenAppStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an option.
        /// </summary>
        public static string SelectAnOption {
            get {
                return ResourceManager.GetString("SelectAnOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github repo, contact information, donations..
        /// </summary>
        public static string SettingsAbout {
            get {
                return ResourceManager.GetString("SettingsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default sort order, themes, etc..
        /// </summary>
        public static string SettingsGeneral {
            get {
                return ResourceManager.GetString("SettingsGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toast notifications..
        /// </summary>
        public static string SettingsNotif {
            get {
                return ResourceManager.GetString("SettingsNotif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background tasks intervals..
        /// </summary>
        public static string SettingsSync {
            get {
                return ResourceManager.GetString("SettingsSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a notification after full sync.
        /// </summary>
        public static string ShowNotifAfterFullSync {
            get {
                return ResourceManager.GetString("ShowNotifAfterFullSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By name asc.
        /// </summary>
        public static string SortByNameAsc {
            get {
                return ResourceManager.GetString("SortByNameAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By name desc.
        /// </summary>
        public static string SortByNameDesc {
            get {
                return ResourceManager.GetString("SortByNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By updated date asc.
        /// </summary>
        public static string SortByUpdatedDateAsc {
            get {
                return ResourceManager.GetString("SortByUpdatedDateAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By updated date desc.
        /// </summary>
        public static string SortByUpdatedDateDesc {
            get {
                return ResourceManager.GetString("SortByUpdatedDateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each 12 hours.
        /// </summary>
        public static string Sync12h {
            get {
                return ResourceManager.GetString("Sync12h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each hour.
        /// </summary>
        public static string Sync1h {
            get {
                return ResourceManager.GetString("Sync1h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each 24 hours.
        /// </summary>
        public static string Sync24h {
            get {
                return ResourceManager.GetString("Sync24h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each 30 minutes.
        /// </summary>
        public static string Sync30m {
            get {
                return ResourceManager.GetString("Sync30m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each 3 hours.
        /// </summary>
        public static string Sync3h {
            get {
                return ResourceManager.GetString("Sync3h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each 6 hours.
        /// </summary>
        public static string Sync6h {
            get {
                return ResourceManager.GetString("Sync6h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A automatic full sync was successfully performed.
        /// </summary>
        public static string SyncAutoCompleted {
            get {
                return ResourceManager.GetString("SyncAutoCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization.
        /// </summary>
        public static string Synchronization {
            get {
                return ResourceManager.GetString("Synchronization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A manual full sync was successfully performed.
        /// </summary>
        public static string SyncManualCompleted {
            get {
                return ResourceManager.GetString("SyncManualCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync results.
        /// </summary>
        public static string SyncResults {
            get {
                return ResourceManager.GetString("SyncResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown synchronization error occurred.
        /// </summary>
        public static string SyncUnknownError {
            get {
                return ResourceManager.GetString("SyncUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task {0} could not be marked as completed.
        /// </summary>
        public static string TaskCouldntBeMarkedAsCompleted {
            get {
                return ResourceManager.GetString("TaskCouldntBeMarkedAsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasklist and Tasks.
        /// </summary>
        public static string TaskListAndTasks {
            get {
                return ResourceManager.GetString("TaskListAndTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task list was succesfully created.
        /// </summary>
        public static string TaskListWasCreated {
            get {
                return ResourceManager.GetString("TaskListWasCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was marked as {1}.
        /// </summary>
        public static string TaskStatusChanged {
            get {
                return ResourceManager.GetString("TaskStatusChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task was successfully created into {0}.
        /// </summary>
        public static string TaskWasCreated {
            get {
                return ResourceManager.GetString("TaskWasCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task successfully moved from: {0} to: {1}.
        /// </summary>
        public static string TaskWasMoved {
            get {
                return ResourceManager.GetString("TaskWasMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title cannot be empty.
        /// </summary>
        public static string TitleCannotBeEmpty {
            get {
                return ResourceManager.GetString("TitleCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title cannot have more than {0} characters.
        /// </summary>
        public static string TitleMaxLength {
            get {
                return ResourceManager.GetString("TitleMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        public static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your password.
        /// </summary>
        public static string TypeYourPassword {
            get {
                return ResourceManager.GetString("TypeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred.
        /// </summary>
        public static string UnknownErrorOccurred {
            get {
                return ResourceManager.GetString("UnknownErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you uninstall the app without signing out ? I will properly log you out now....
        /// </summary>
        public static string UnnistalledAppWithoutSigningOut {
            get {
                return ResourceManager.GetString("UnnistalledAppWithoutSigningOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Task.
        /// </summary>
        public static string UpdateTask {
            get {
                return ResourceManager.GetString("UpdateTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out?.
        /// </summary>
        public static string WannaLogOut {
            get {
                return ResourceManager.GetString("WannaLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Mirai Notes.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        public static string XDayAgo {
            get {
                return ResourceManager.GetString("XDayAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
